import type { Metadata } from "next";
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import ThemeProvider from "@/components/providers/ThemeProvider"


export const metadata: Metadata = {
  title: "CMA PLATFORM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
